package com.app.wms.hbm.bean;
// Generated Dec 26, 2012 8:48:26 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CorpUser generated by hbm2java
 */
public class CorpUser  implements java.io.Serializable {


     private String corpuserId;
     private String corpId;
     private String userId;
     private Character isActive;
     private Character isDelete;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public CorpUser() {
    }

	
    public CorpUser(String corpuserId) {
        this.corpuserId = corpuserId;
    }
    public CorpUser(String corpuserId, String corpId, String userId, Character isActive, Character isDelete, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.corpuserId = corpuserId;
       this.corpId = corpId;
       this.userId = userId;
       this.isActive = isActive;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public String getCorpuserId() {
        return this.corpuserId;
    }
    
    public void setCorpuserId(String corpuserId) {
        this.corpuserId = corpuserId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }
    public Character getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


