package com.app.wms.hbm.bean;
// Generated Dec 5, 2012 11:54:05 PM by Hibernate Tools 3.2.1.GA



/**
 * CrossdockDetail generated by hbm2java
 */
public class CrossdockDetail  implements java.io.Serializable {


     private int id;
     private String ponumber;
     private String productcode;
     private Integer qty;
     private String location;
     private String description;

    public CrossdockDetail() {
    }

	
    public CrossdockDetail(int id) {
        this.id = id;
    }
    public CrossdockDetail(int id, String ponumber, String productcode, Integer qty, String location, String description) {
       this.id = id;
       this.ponumber = ponumber;
       this.productcode = productcode;
       this.qty = qty;
       this.location = location;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPonumber() {
        return this.ponumber;
    }
    
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


