package com.app.wms.hbm.bean;
// Generated Dec 5, 2012 11:54:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Crossdock generated by hbm2java
 */
public class Crossdock  implements java.io.Serializable {


     private int id;
     private String consigneenumber;
     private Date receivedate;
     private String ponumber;
     private String corpId;
     private String whId;
     private String createdby;

    public Crossdock() {
    }

	
    public Crossdock(int id) {
        this.id = id;
    }
    public Crossdock(int id, String consigneenumber, Date receivedate, String ponumber, String corpId, String whId, String createdby) {
       this.id = id;
       this.consigneenumber = consigneenumber;
       this.receivedate = receivedate;
       this.ponumber = ponumber;
       this.corpId = corpId;
       this.whId = whId;
       this.createdby = createdby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getConsigneenumber() {
        return this.consigneenumber;
    }
    
    public void setConsigneenumber(String consigneenumber) {
        this.consigneenumber = consigneenumber;
    }
    public Date getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(Date receivedate) {
        this.receivedate = receivedate;
    }
    public String getPonumber() {
        return this.ponumber;
    }
    
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhId() {
        return this.whId;
    }
    
    public void setWhId(String whId) {
        this.whId = whId;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


