package com.app.wms.hbm.bean;
// Generated Nov 15, 2012 6:19:04 PM by Hibernate Tools 3.2.1.GA


import java.sql.Clob;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private String customercode;
     private String customername;
     private String customeraddress;

    public Customer() {
    }

	
    public Customer(int id) {
        this.id = id;
    }
    public Customer(int id, String customercode, String customername, String customeraddress) {
       this.id = id;
       this.customercode = customercode;
       this.customername = customername;
       this.customeraddress = customeraddress;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCustomercode() {
        return this.customercode;
    }
    
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }
    public String getCustomername() {
        return this.customername;
    }
    
    public void setCustomername(String customername) {
        this.customername = customername;
    }
    public String getCustomeraddress() {
        return this.customeraddress;
    }
    
    public void setCustomeraddress(String customeraddress) {
        this.customeraddress = customeraddress;
    }




}


