package com.app.wms.hbm.bean;
// Generated Nov 23, 2012 11:35:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Goodreceive generated by hbm2java
 */
public class Goodreceive  implements java.io.Serializable {

     private int id;
     private String grnumber;
     private String ponumber;
     private Date receiveddate;
     private String createdby;
     private String corpid;
     private String whCode;
     private String lotid;
     private String wsNo;
     private Integer unitCost;
     private Integer amount;
     private String checkedBy;
     private String accEntry;
     private String evalBy;
     private String appBy;
     private String departmentName;

    public Goodreceive() {
    }
	
    public Goodreceive(int id) {
        this.id = id;
    }
    public Goodreceive(int id, String grnumber, String ponumber, Date receiveddate, String createdby, String corpid) {
       this.id = id;
       this.grnumber = grnumber;
       this.ponumber = ponumber;
       this.receiveddate = receiveddate;
       this.createdby = createdby;
       this.corpid = corpid;
    }
   
    public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getWsNo() {
		return wsNo;
	}

	public void setWsNo(String wsNo) {
		this.wsNo = wsNo;
	}

	public Integer getUnitCost() {
		return unitCost;
	}

	public void setUnitCost(Integer unitCost) {
		this.unitCost = unitCost;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getCheckedBy() {
		return checkedBy;
	}

	public void setCheckedBy(String checkedBy) {
		this.checkedBy = checkedBy;
	}

	public String getAccEntry() {
		return accEntry;
	}

	public void setAccEntry(String accEntry) {
		this.accEntry = accEntry;
	}

	public String getEvalBy() {
		return evalBy;
	}

	public void setEvalBy(String evalBy) {
		this.evalBy = evalBy;
	}

	public String getAppBy() {
		return appBy;
	}

	public void setAppBy(String appBy) {
		this.appBy = appBy;
	}

	public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGrnumber() {
        return this.grnumber;
    }
    
    public void setGrnumber(String grnumber) {
        this.grnumber = grnumber;
    }
    public String getPonumber() {
        return this.ponumber;
    }
    
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }
    public Date getReceiveddate() {
        return this.receiveddate;
    }
    
    public void setReceiveddate(Date receiveddate) {
        this.receiveddate = receiveddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getCorpid() {
        return this.corpid;
    }
    
    public void setCorpid(String corpid) {
        this.corpid = corpid;
    }

    public String getLotid() {
        return lotid;
    }

    public void setLotid(String lotid) {
        this.lotid = lotid;
    }

    public String getWhCode() {
        return whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

}