package com.app.wms.hbm.bean;
// Generated Nov 23, 2012 11:35:17 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * GoodreceiveDetail generated by hbm2java
 */
public class GoodreceiveDetail  implements java.io.Serializable {


     private int id;
     private String grnumber;
     private String productcode;
     private BigDecimal qtyreal;
     private String status;
     private Date expirydate;
     private String remark;
     private String producttype;
     private Integer lotid;
     private BigDecimal qtygood;
     private BigDecimal qtydmg;
    

    public GoodreceiveDetail() {
    }

	
    public GoodreceiveDetail(int id) {
        this.id = id;
    }

    public GoodreceiveDetail(int id, String grnumber, String productcode, BigDecimal qtyreal, String status, Date expirydate, String remark, Integer lotid, BigDecimal qtygood, BigDecimal qtydmg) {
        this.id = id;
        this.grnumber = grnumber;
        this.productcode = productcode;
        this.qtyreal = qtyreal;
        this.status = status;
        this.expirydate = expirydate;
        this.remark = remark;
        this.lotid = lotid;
        this.qtygood = qtygood;
        this.qtydmg = qtydmg;
    }


	public BigDecimal getQtyreal() {
		return qtyreal;
	}


	public void setQtyreal(BigDecimal qtyreal) {
		this.qtyreal = qtyreal;
	}


	public BigDecimal getQtygood() {
		return qtygood;
	}


	public void setQtygood(BigDecimal qtygood) {
		this.qtygood = qtygood;
	}


	public BigDecimal getQtydmg() {
		return qtydmg;
	}


	public void setQtydmg(BigDecimal qtydmg) {
		this.qtydmg = qtydmg;
	}


	public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGrnumber() {
        return this.grnumber;
    }
    
    public void setGrnumber(String grnumber) {
        this.grnumber = grnumber;
    }
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
    
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Integer getLotid() {
        return this.lotid;
    }
    
    public void setLotid(Integer lotid) {
        this.lotid = lotid;
    }


    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + this.id;
        hash = 23 * hash + (this.grnumber != null ? this.grnumber.hashCode() : 0);
        hash = 23 * hash + (this.productcode != null ? this.productcode.hashCode() : 0);
        hash = 23 * hash + (this.qtyreal != null ? this.qtyreal.hashCode() : 0);
        hash = 23 * hash + (this.status != null ? this.status.hashCode() : 0);
        hash = 23 * hash + (this.expirydate != null ? this.expirydate.hashCode() : 0);
        hash = 23 * hash + (this.remark != null ? this.remark.hashCode() : 0);
        hash = 23 * hash + (this.producttype != null ? this.producttype.hashCode() : 0);
        hash = 23 * hash + (this.lotid != null ? this.lotid.hashCode() : 0);
        hash = 23 * hash + (this.qtygood != null ? this.qtygood.hashCode() : 0);
        hash = 23 * hash + (this.qtydmg != null ? this.qtydmg.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GoodreceiveDetail other = (GoodreceiveDetail) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.grnumber == null) ? (other.grnumber != null) : !this.grnumber.equals(other.grnumber)) {
            return false;
        }
        if ((this.productcode == null) ? (other.productcode != null) : !this.productcode.equals(other.productcode)) {
            return false;
        }
        if (this.qtyreal != other.qtyreal && (this.qtyreal == null || !this.qtyreal.equals(other.qtyreal))) {
            return false;
        }
        if ((this.status == null) ? (other.status != null) : !this.status.equals(other.status)) {
            return false;
        }
        if (this.expirydate != other.expirydate && (this.expirydate == null || !this.expirydate.equals(other.expirydate))) {
            return false;
        }
        if ((this.remark == null) ? (other.remark != null) : !this.remark.equals(other.remark)) {
            return false;
        }
        if ((this.producttype == null) ? (other.producttype != null) : !this.producttype.equals(other.producttype)) {
            return false;
        }
        if (this.lotid != other.lotid && (this.lotid == null || !this.lotid.equals(other.lotid))) {
            return false;
        }
        if (this.qtygood != other.qtygood && (this.qtygood == null || !this.qtygood.equals(other.qtygood))) {
            return false;
        }
        if (this.qtydmg != other.qtydmg && (this.qtydmg == null || !this.qtydmg.equals(other.qtydmg))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "GoodreceiveDetail{" + "id=" + id + ", grnumber=" + grnumber + ", productcode=" + productcode + ", qtyreal=" + qtyreal + ", status=" + status + ", expirydate=" + expirydate + ", remark=" + remark + ", producttype=" + producttype + ", lotid=" + lotid + ", qtygood=" + qtygood + ", qtydmg=" + qtydmg + '}';
    }

    public String getProducttype() {
        return producttype;
    }

    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

}


