package com.app.wms.hbm.bean;
// Generated Nov 23, 2012 12:35:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Po generated by hbm2java
 */
public class Po  implements java.io.Serializable {


     private long id;
     private String ponumber;
     private Date podate;
     private String prsnumber;
     private Date prsdate;
     private Date deliverydate;
     private String poreferensi;
     private String createdby;
     private String corpid;
     private String whCode;
     private String departmentName;
     private String supplierName;
     private String currencyCode;
     private String prsremarks;
     private String roleCode;
     private String status;
     private Date statusdate;

    public Po() {
    }

	
    public Po(long id) {
        this.id = id;
    }
    public Po(long id, String ponumber, Date podate, String prsnumber, Date prsdate, Date deliverydate, String poreferensi, String createdby, String corpid, String whCode, String departmentName, String supplierName, String currencyCode, String prsremarks, String roleCode, String status, Date statusdate) {
       this.id = id;
       this.ponumber = ponumber;
       this.podate = podate;
       this.prsnumber = prsnumber;
       this.prsdate = prsdate;
       this.deliverydate = deliverydate;
       this.poreferensi = poreferensi;
       this.createdby = createdby;
       this.corpid = corpid;
       this.whCode = whCode;
       this.currencyCode = currencyCode;
       this.prsremarks = prsremarks;
       this.roleCode = roleCode;
       this.status = status;
       this.statusdate = statusdate;
       
    }
   
    public Date getStatusdate() {
		return statusdate;
	}


	public void setStatusdate(Date statusdate) {
		this.statusdate = statusdate;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getRoleCode() {
		return roleCode;
	}


	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}


	public Date getPodate() {
		return podate;
	}


	public void setPodate(Date podate) {
		this.podate = podate;
	}


	public Date getPrsdate() {
		return prsdate;
	}


	public void setPrsdate(Date prsdate) {
		this.prsdate = prsdate;
	}


	public String getCurrencyCode() {
		return currencyCode;
	}


	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}


	public String getPrsremarks() {
		return prsremarks;
	}


	public void setPrsremarks(String prsremarks) {
		this.prsremarks = prsremarks;
	}


	public String getPrsnumber() {
		return prsnumber;
	}


	public void setPrsnumber(String prsnumber) {
		this.prsnumber = prsnumber;
	}


	public String getDepartmentName() {
		return departmentName;
	}


	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}


	public String getSupplierName() {
		return supplierName;
	}


	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}


	public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getPonumber() {
        return this.ponumber;
    }
    
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    public String getPoreferensi() {
        return this.poreferensi;
    }
    
    public void setPoreferensi(String poreferensi) {
        this.poreferensi = poreferensi;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getCorpid() {
        return this.corpid;
    }
    
    public void setCorpid(String corpid) {
        this.corpid = corpid;
    }

    public String getWhCode() {
        return whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

}
