package com.app.wms.hbm.bean;

import java.math.BigDecimal;
import java.util.Date;

// Generated Nov 23, 2012 12:39:11 AM by Hibernate Tools 3.2.1.GA



/**
 * PoDetail generated by hbm2java
 */
public class PoDetail  implements java.io.Serializable {

     private int id;
     private String ponumber;
     private String productcode;
     private BigDecimal qty;
     private String producttype;
     private String uom;
     private BigDecimal unitprice;
     private BigDecimal amount;
     private BigDecimal ppn;
     private String poremarks;
     private String currencyCode;
     private Date warranty;
     private String termpayment;
     private String termdelivery;
     private BigDecimal discount;
     private BigDecimal pph;
     private BigDecimal total;

    public PoDetail() {
    }

	
    public PoDetail(int id) {
        this.id = id;
    }
    public PoDetail(int id, String ponumber, String productcode, BigDecimal qty, String producttype, String uom, BigDecimal unitprice, BigDecimal amount, BigDecimal ppn, String poremarks, String currencyCode, Date warranty, String termpayment, String termdelivery, BigDecimal discount, BigDecimal pph, BigDecimal total) {
       this.id = id;
       this.ponumber = ponumber;
       this.productcode = productcode;
       this.qty = qty;
       this.producttype = producttype;
       this.uom = uom;
       this.unitprice = unitprice;
       this.amount = amount;
       this.ppn = ppn;
       this.poremarks = poremarks;
       this.currencyCode = currencyCode;
       this.warranty = warranty;
       this.termpayment = termpayment;
       this.termdelivery = termdelivery;
       this.discount = discount;
       this.pph = pph;
       this.total = total;
    }
   
    public Date getWarranty() {
		return warranty;
	}


	public void setWarranty(Date warranty) {
		this.warranty = warranty;
	}


	public String getTermpayment() {
		return termpayment;
	}


	public void setTermpayment(String termpayment) {
		this.termpayment = termpayment;
	}


	public String getTermdelivery() {
		return termdelivery;
	}


	public void setTermdelivery(String termdelivery) {
		this.termdelivery = termdelivery;
	}


	public BigDecimal getDiscount() {
		return discount;
	}


	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}


	public BigDecimal getPph() {
		return pph;
	}


	public void setPph(BigDecimal pph) {
		this.pph = pph;
	}


	public BigDecimal getTotal() {
		return total;
	}


	public void setTotal(BigDecimal total) {
		this.total = total;
	}


	public BigDecimal getQty() {
		return qty;
	}


	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}


	public String getCurrencyCode() {
		return currencyCode;
	}


	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}


	public String getPoremarks() {
		return poremarks;
	}


	public void setPoremarks(String poremarks) {
		this.poremarks = poremarks;
	}


	public String getUom() {
		return uom;
	}


	public void setUom(String uom) {
		this.uom = uom;
	}


	public BigDecimal getUnitprice() {
		return unitprice;
	}


	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}


	public BigDecimal getAmount() {
		return amount;
	}


	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}


	public BigDecimal getPpn() {
		return ppn;
	}


	public void setPpn(BigDecimal ppn) {
		this.ppn = ppn;
	}


	public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPonumber() {
        return this.ponumber;
    }
    
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
    
    public String getProducttype() {
        return this.producttype;
    }
    
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }




}


