package com.app.wms.hbm.bean;
// Generated Feb 6, 2013 3:13:24 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private String productId;
     private String barCode;
     private String productCode;
     private String productName;
     private String productAlias;
     private String productCategory;
     private String brandName;
     private String productType;
     private String productColor;
     private String productDescription;
     private String volumeWeight;
     private String unitWeight;
     private String volumeMatrix;
     private String unitMatrix;
     private String unitLength;
     private String unitWidth;
     private String unitHeight;
     private Integer unitPiece;
     private Integer unitBox;
     private Integer unitCartoon;
     private Integer unitPallete;
     private String userId;
     private String corpId;
     private String whCode;
     private Character isActive;
     private Character isDelete;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String uom;

    public Product() {
    }

	
    public Product(int id, Date createdDate, Date updatedDate) {
        this.id = id;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Product(int id, String productId, String barCode, String productCode, String productName, String productAlias, String productCategory, String brandName, String productType, String productColor, String productDescription, String volumeWeight, String unitWeight, String volumeMatrix, String unitMatrix, String unitLength, String unitWidth, String unitHeight, Integer unitPiece, Integer unitBox, Integer unitCartoon, Integer unitPallete, String userId, String corpId, String whCode, Character isActive, Character isDelete, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String uom) {
       this.id = id;
       this.productId = productId;
       this.barCode = barCode;
       this.productCode = productCode;
       this.productName = productName;
       this.productAlias = productAlias;
       this.productCategory = productCategory;
       this.brandName = brandName;
       this.productType = productType;
       this.productColor = productColor;
       this.productDescription = productDescription;
       this.volumeWeight = volumeWeight;
       this.unitWeight = unitWeight;
       this.volumeMatrix = volumeMatrix;
       this.unitMatrix = unitMatrix;
       this.unitLength = unitLength;
       this.unitWidth = unitWidth;
       this.unitHeight = unitHeight;
       this.unitPiece = unitPiece;
       this.unitBox = unitBox;
       this.unitCartoon = unitCartoon;
       this.unitPallete = unitPallete;
       this.userId = userId;
       this.corpId = corpId;
       this.whCode = whCode;
       this.isActive = isActive;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.uom = uom;
    }
   
    public String getUom() {
		return uom;
	}


	public void setUom(String uom) {
		this.uom = uom;
	}


	public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductAlias() {
        return this.productAlias;
    }
    
    public void setProductAlias(String productAlias) {
        this.productAlias = productAlias;
    }
    public String getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public String getVolumeWeight() {
        return this.volumeWeight;
    }
    
    public void setVolumeWeight(String volumeWeight) {
        this.volumeWeight = volumeWeight;
    }
    public String getUnitWeight() {
        return this.unitWeight;
    }
    
    public void setUnitWeight(String unitWeight) {
        this.unitWeight = unitWeight;
    }
    public String getVolumeMatrix() {
        return this.volumeMatrix;
    }
    
    public void setVolumeMatrix(String volumeMatrix) {
        this.volumeMatrix = volumeMatrix;
    }
    public String getUnitMatrix() {
        return this.unitMatrix;
    }
    
    public void setUnitMatrix(String unitMatrix) {
        this.unitMatrix = unitMatrix;
    }
    public String getUnitLength() {
        return this.unitLength;
    }
    
    public void setUnitLength(String unitLength) {
        this.unitLength = unitLength;
    }
    public String getUnitWidth() {
        return this.unitWidth;
    }
    
    public void setUnitWidth(String unitWidth) {
        this.unitWidth = unitWidth;
    }
    public String getUnitHeight() {
        return this.unitHeight;
    }
    
    public void setUnitHeight(String unitHeight) {
        this.unitHeight = unitHeight;
    }
    public Integer getUnitPiece() {
        return this.unitPiece;
    }
    
    public void setUnitPiece(Integer unitPiece) {
        this.unitPiece = unitPiece;
    }
    public Integer getUnitBox() {
        return this.unitBox;
    }
    
    public void setUnitBox(Integer unitBox) {
        this.unitBox = unitBox;
    }
    public Integer getUnitCartoon() {
        return this.unitCartoon;
    }
    
    public void setUnitCartoon(Integer unitCartoon) {
        this.unitCartoon = unitCartoon;
    }
    public Integer getUnitPallete() {
        return this.unitPallete;
    }
    
    public void setUnitPallete(Integer unitPallete) {
        this.unitPallete = unitPallete;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }
    public Character getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


