package com.app.wms.hbm.bean;
// Generated Nov 25, 2012 11:25:12 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Putaway generated by hbm2java
 */
public class Putaway  implements java.io.Serializable {


     private String putawayId;
     private Date putawayDate;
     private String grNumber;     
     private Date grDate;
     private String statusApp;
     private Date appDate;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private String tallyman;
     private Date updatedDate;

    public Putaway() {
    }

	
    public Putaway(String putawayId) {
        this.putawayId = putawayId;
    }
    public Putaway(String putawayId, Date putawayDate, String grNumber, Date grDate, String statusApp, Date appDate, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.putawayId = putawayId;
       this.putawayDate = putawayDate;
       this.grNumber = grNumber;
       this.grDate = grDate;
       this.statusApp = statusApp;
       this.appDate = appDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public String getPutawayId() {
        return this.putawayId;
    }
    
    public void setPutawayId(String putawayId) {
        this.putawayId = putawayId;
    }
    public Date getPutawayDate() {
        return this.putawayDate;
    }
    
    public void setPutawayDate(Date putawayDate) {
        this.putawayDate = putawayDate;
    }
    public String getGrNumber() {
        return this.grNumber;
    }
    
    public void setGrNumber(String grNumber) {
        this.grNumber = grNumber;
    }
    public Date getGrDate() {
        return this.grDate;
    }
    
    public void setGrDate(Date grDate) {
        this.grDate = grDate;
    }
    public String getStatusApp() {
        return this.statusApp;
    }
    
    public void setStatusApp(String statusApp) {
        this.statusApp = statusApp;
    }
    public Date getAppDate() {
        return this.appDate;
    }
    
    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getTallyman() {
        return tallyman;
    }

    public void setTallyman(String tallyman) {
        this.tallyman = tallyman;
    }



}


