package com.app.wms.hbm.bean;
// Generated Nov 25, 2012 11:25:12 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.UUID;

/**
 * PutawayDetail generated by hbm2java
 */
public class PutawayDetail  implements java.io.Serializable {


     private int id;
     private Integer lotid;
     private String putawayId;
     private String productId;
     private String productCode;
     private Date receivedDate;
     private Date expiredDate;
     private String unitCode;
     private Integer qtyOrder;
     private Integer qtyPut;
     private Integer balance;
     private String userId;
     private String corpId;
     private String locationCode;
     private String whCode;
     private String productType;

    public PutawayDetail() {
    }

	
    public PutawayDetail(int id) {
        this.id = id;
    }
    public PutawayDetail(int id, String putawayId, String productId, Date receivedDate, Date expiredDate, String unitCode, Integer qtyOrder, Integer qtyPut, Integer balance, String userId, String corpId, String locationCode, String whCode) {
       this.id = id;
       this.putawayId = putawayId;
       this.productId = productId;
       this.receivedDate = receivedDate;
       this.expiredDate = expiredDate;
       this.unitCode = unitCode;
       this.qtyOrder = qtyOrder;
       this.qtyPut = qtyPut;
       this.balance = balance;
       this.userId = userId;
       this.corpId = corpId;
       this.locationCode = locationCode;
       this.whCode = whCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPutawayId() {
        return this.putawayId;
    }
    
    public void setPutawayId(String putawayId) {
        this.putawayId = putawayId;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    public Date getExpiredDate() {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }
    public String getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }
    public Integer getQtyOrder() {
        return this.qtyOrder;
    }
    
    public void setQtyOrder(Integer qtyOrder) {
        this.qtyOrder = qtyOrder;
    }
    public Integer getQtyPut() {
        return this.qtyPut;
    }
    
    public void setQtyPut(Integer qtyPut) {
        this.qtyPut = qtyPut;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }   

    public Integer getLotid() {
        return lotid;
    }

    public void setLotid(Integer lotid) {
        this.lotid = lotid;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + this.id;
        hash = 71 * hash + (this.lotid != null ? this.lotid.hashCode() : 0);
        hash = 71 * hash + (this.putawayId != null ? this.putawayId.hashCode() : 0);
        hash = 71 * hash + (this.productId != null ? this.productId.hashCode() : 0);
        hash = 71 * hash + (this.productCode != null ? this.productCode.hashCode() : 0);
        hash = 71 * hash + (this.receivedDate != null ? this.receivedDate.hashCode() : 0);
        hash = 71 * hash + (this.expiredDate != null ? this.expiredDate.hashCode() : 0);
        hash = 71 * hash + (this.unitCode != null ? this.unitCode.hashCode() : 0);
        hash = 71 * hash + (this.qtyOrder != null ? this.qtyOrder.hashCode() : 0);
        hash = 71 * hash + (this.qtyPut != null ? this.qtyPut.hashCode() : 0);
        hash = 71 * hash + (this.balance != null ? this.balance.hashCode() : 0);
        hash = 71 * hash + (this.userId != null ? this.userId.hashCode() : 0);
        hash = 71 * hash + (this.corpId != null ? this.corpId.hashCode() : 0);
        hash = 71 * hash + (this.locationCode != null ? this.locationCode.hashCode() : 0);
        hash = 71 * hash + (this.whCode != null ? this.whCode.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PutawayDetail other = (PutawayDetail) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.lotid != other.lotid && (this.lotid == null || !this.lotid.equals(other.lotid))) {
            return false;
        }
        if ((this.putawayId == null) ? (other.putawayId != null) : !this.putawayId.equals(other.putawayId)) {
            return false;
        }
        if ((this.productId == null) ? (other.productId != null) : !this.productId.equals(other.productId)) {
            return false;
        }
        if ((this.productCode == null) ? (other.productCode != null) : !this.productCode.equals(other.productCode)) {
            return false;
        }
        if (this.receivedDate != other.receivedDate && (this.receivedDate == null || !this.receivedDate.equals(other.receivedDate))) {
            return false;
        }
        if (this.expiredDate != other.expiredDate && (this.expiredDate == null || !this.expiredDate.equals(other.expiredDate))) {
            return false;
        }
        if ((this.unitCode == null) ? (other.unitCode != null) : !this.unitCode.equals(other.unitCode)) {
            return false;
        }
        if (this.qtyOrder != other.qtyOrder && (this.qtyOrder == null || !this.qtyOrder.equals(other.qtyOrder))) {
            return false;
        }
        if (this.qtyPut != other.qtyPut && (this.qtyPut == null || !this.qtyPut.equals(other.qtyPut))) {
            return false;
        }
        if (this.balance != other.balance && (this.balance == null || !this.balance.equals(other.balance))) {
            return false;
        }
        if ((this.userId == null) ? (other.userId != null) : !this.userId.equals(other.userId)) {
            return false;
        }
        if ((this.corpId == null) ? (other.corpId != null) : !this.corpId.equals(other.corpId)) {
            return false;
        }
        if ((this.locationCode == null) ? (other.locationCode != null) : !this.locationCode.equals(other.locationCode)) {
            return false;
        }
        if ((this.whCode == null) ? (other.whCode != null) : !this.whCode.equals(other.whCode)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "PutawayDetail{" + "id=" + id + ", lotid=" + lotid + ", putawayId=" + putawayId + ", productId=" + productId + ", productCode=" + productCode + ", receivedDate=" + receivedDate + ", expiredDate=" + expiredDate + ", unitCode=" + unitCode + ", qtyOrder=" + qtyOrder + ", qtyPut=" + qtyPut + ", balance=" + balance + ", userId=" + userId + ", corpId=" + corpId + ", locationCode=" + locationCode + ", whCode=" + whCode + ", productType=" + productType + '}';
    }

    

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    
    
    

    
}


