package com.app.wms.hbm.bean;
// Generated Jan 1, 2013 11:50:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Stocktake generated by hbm2java
 */
public class Stocktake  implements java.io.Serializable {


     private int id;
     private String productcode;
     private Integer qty;
     private Integer actualqty;
     private String corpId;
     private String whCode;
     private String userId;
     private Date stockdate;
     private String stockname;
     private String locationcode;
     private Boolean approved;

    public Stocktake() {
    }

	
    public Stocktake(int id) {
        this.id = id;
    }
    public Stocktake(int id, String productcode, Integer qty, Integer actualqty, String corpId, String whCode, String userId, Date stockdate, String stockname, Boolean approved) {
       this.id = id;
       this.productcode = productcode;
       this.qty = qty;
       this.actualqty = actualqty;
       this.corpId = corpId;
       this.whCode = whCode;
       this.userId = userId;
       this.stockdate = stockdate;
       this.stockname = stockname;
       this.approved = approved;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getActualqty() {
        return this.actualqty;
    }
    
    public void setActualqty(Integer actualqty) {
        this.actualqty = actualqty;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getStockdate() {
        return this.stockdate;
    }
    
    public void setStockdate(Date stockdate) {
        this.stockdate = stockdate;
    }
    public String getStockname() {
        return this.stockname;
    }
    
    public void setStockname(String stockname) {
        this.stockname = stockname;
    }
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    public String getLocationcode() {
        return locationcode;
    }

    public void setLocationcode(String locationcode) {
        this.locationcode = locationcode;
    }

    @Override
    public String toString() {
        return "Stocktake{" + "id=" + id + ", productcode=" + productcode + ", qty=" + qty + ", actualqty=" + actualqty + ", corpId=" + corpId + ", whCode=" + whCode + ", userId=" + userId + ", stockdate=" + stockdate + ", stockname=" + stockname + ", locationcode=" + locationcode + ", approved=" + approved + '}';
    }




}


