package com.app.wms.hbm.bean;
// Generated Nov 22, 2012 8:23:21 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tallyman generated by hbm2java
 */
public class Tallyman  implements java.io.Serializable {


     private int id;
//     private String tallyId;
     private String code;
     private String name;
     private String tallyname;
     private String jobfunction;
     private String corpId;
     private String whCode;
     private Character isActive;
     private Character isDelete;
     private Integer createdBy;
     private Date createdDate;
     private Integer updatedBy;
     private Date updatedDate;

    public Tallyman() {
    }

	
    public Tallyman(int id, Date createdDate, Date updatedDate) {
        this.id = id;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Tallyman(int id, String code, String name, String tallyname, String jobfunction, String corpId, String whCode, Character isActive, Character isDelete, Integer createdBy, Date createdDate, Integer updatedBy, Date updatedDate) {
       this.id = id;
//       this.tallyId = tallyId;
       this.code = code;
       this.name = name;
       this.tallyname = tallyname;
       this.jobfunction = jobfunction;
       this.corpId = corpId;
       this.whCode = whCode;
       this.isActive = isActive;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
//    public String getTallyId() {
//        return this.tallyId;
//    }
//    
//    public void setTallyId(String tallyId) {
//        this.tallyId = tallyId;
//    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTallyname() {
        return this.tallyname;
    }
    
    public void setTallyname(String tallyname) {
        this.tallyname = tallyname;
    }
    public String getJobfunction() {
        return this.jobfunction;
    }
    
    public void setJobfunction(String jobfunction) {
        this.jobfunction = jobfunction;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }
    public Character getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


