package com.app.wms.hbm.bean;
// Generated Dec 19, 2012 4:29:03 PM by Hibernate Tools 3.2.1.GA



/**
 * Vbalanceputawaydetail generated by hbm2java
 */
public class Vbalanceputawaydetail  implements java.io.Serializable {

private Integer balance;
     private String locationCode;
     

    public Vbalanceputawaydetail() {
    }

    public Vbalanceputawaydetail(Integer balance, String locationCode, Integer id) {
       this.balance = balance;
       this.locationCode = locationCode;
       
    }
   
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }
   


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vbalanceputawaydetail) ) return false;
		 Vbalanceputawaydetail castOther = ( Vbalanceputawaydetail ) other; 
         
		 return ( (this.getBalance()==castOther.getBalance()) || ( this.getBalance()!=null && castOther.getBalance()!=null && this.getBalance().equals(castOther.getBalance()) ) )
 && ( (this.getLocationCode()==castOther.getLocationCode()) || ( this.getLocationCode()!=null && castOther.getLocationCode()!=null && this.getLocationCode().equals(castOther.getLocationCode()) ) )
 ;
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBalance() == null ? 0 : this.getBalance().hashCode() );
         result = 37 * result + ( getLocationCode() == null ? 0 : this.getLocationCode().hashCode() );         
         return result;
   }   

    @Override
    public String toString() {
        return "Vbalanceputawaydetail{" + "balance=" + balance + ", locationCode=" + locationCode + " }";
    }



}


