package com.app.wms.hbm.bean;

import java.math.BigDecimal;
// Generated Nov 23, 2012 7:30:57 PM by Hibernate Tools 3.2.1.GA

/**
 * Vgrdetailproduct generated by hbm2java
 */
public class Vgrdetailproduct implements java.io.Serializable {

    private String productName;
    private String productCode;
    private int id;
    private String ponumber;
    private String productcode;
    private BigDecimal qty;
    private String producttype;
    private String whCode;
    private String corpId;

    public BigDecimal getQty() {
		return qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPonumber() {
        return this.ponumber;
    }

    public void setPonumber(String ponumber) {
        this.ponumber = ponumber;
    }

    public String getProductcode() {
        return this.productcode;
    }

    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    public String getProducttype() {
        return this.producttype;
    }

    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof Vgrdetailproduct)) {
            return false;
        }
        Vgrdetailproduct castOther = (Vgrdetailproduct) other;

        return ((this.getProductName() == castOther.getProductName()) || (this.getProductName() != null && castOther.getProductName() != null && this.getProductName().equals(castOther.getProductName())))
                && ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null && castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
                && (this.getId() == castOther.getId())
                && ((this.getPonumber() == castOther.getPonumber()) || (this.getPonumber() != null && castOther.getPonumber() != null && this.getPonumber().equals(castOther.getPonumber())))
                && ((this.getProductcode() == castOther.getProductcode()) || (this.getProductcode() != null && castOther.getProductcode() != null && this.getProductcode().equals(castOther.getProductcode())))
                && ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null && this.getQty().equals(castOther.getQty())))
                && ((this.getProducttype() == castOther.getProducttype()) || (this.getProducttype() != null && castOther.getProducttype() != null && this.getProducttype().equals(castOther.getProducttype())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProductName() == null ? 0 : this.getProductName().hashCode());
        result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
        result = 37 * result + this.getId();
        result = 37 * result + (getPonumber() == null ? 0 : this.getPonumber().hashCode());
        result = 37 * result + (getProductcode() == null ? 0 : this.getProductcode().hashCode());
        result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
        result = 37 * result + (getProducttype() == null ? 0 : this.getProducttype().hashCode());
        return result;
    }

    public Vgrdetailproduct() {
    }

    public String getWhCode() {
        return whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

    public String getCorpId() {
        return corpId;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    
    
}
