package com.app.wms.hbm.bean;
// Generated Nov 25, 2012 9:49:04 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Vgrdetailproductcategory generated by hbm2java
 */
public class Vgrdetailproductcategory  implements java.io.Serializable {


      private int id;
     private String grnumber;
     private String productcode;
     private Integer qtyreal;
     private String status;
     private Date expirydate;
     private String remark;
     private Integer lotid;
     private String productName;
     private String categoryName;
     private String productType;
     private String corpId;
     private String whCode;
     
      private Integer qtygood;
       private Integer qtydmg;
       private Integer qtyplus;

    public Vgrdetailproductcategory() {
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

	
    
    
    
    
   
    public String getGrnumber() {
        return this.grnumber;
    }
    
    public void setGrnumber(String grnumber) {
        this.grnumber = grnumber;
    }
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
    public Integer getQtyreal() {
        return this.qtyreal;
    }
    
    public void setQtyreal(Integer qtyreal) {
        this.qtyreal = qtyreal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Integer getLotid() {
        return this.lotid;
    }
    
    public void setLotid(Integer lotid) {
        this.lotid = lotid;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Integer getQtygood() {
        return qtygood;
    }

    public void setQtygood(Integer qtygood) {
        this.qtygood = qtygood;
    }

    public Integer getQtydmg() {
        return qtydmg;
    }

    public void setQtydmg(Integer qtydmg) {
        this.qtydmg = qtydmg;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        
        hash = 29 * hash + (this.grnumber != null ? this.grnumber.hashCode() : 0);
        hash = 29 * hash + (this.productcode != null ? this.productcode.hashCode() : 0);
        hash = 29 * hash + (this.qtyreal != null ? this.qtyreal.hashCode() : 0);
        hash = 29 * hash + (this.status != null ? this.status.hashCode() : 0);
        hash = 29 * hash + (this.expirydate != null ? this.expirydate.hashCode() : 0);
        hash = 29 * hash + (this.remark != null ? this.remark.hashCode() : 0);
        hash = 29 * hash + (this.lotid != null ? this.lotid.hashCode() : 0);
        hash = 29 * hash + (this.productName != null ? this.productName.hashCode() : 0);
        hash = 29 * hash + (this.categoryName != null ? this.categoryName.hashCode() : 0);
        hash = 29 * hash + (this.qtygood != null ? this.qtygood.hashCode() : 0);
        hash = 29 * hash + (this.qtydmg != null ? this.qtydmg.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Vgrdetailproductcategory other = (Vgrdetailproductcategory) obj;
        
        if ((this.grnumber == null) ? (other.grnumber != null) : !this.grnumber.equals(other.grnumber)) {
            return false;
        }
        if ((this.productcode == null) ? (other.productcode != null) : !this.productcode.equals(other.productcode)) {
            return false;
        }
        if (this.qtyreal != other.qtyreal && (this.qtyreal == null || !this.qtyreal.equals(other.qtyreal))) {
            return false;
        }
        if ((this.status == null) ? (other.status != null) : !this.status.equals(other.status)) {
            return false;
        }
        if (this.expirydate != other.expirydate && (this.expirydate == null || !this.expirydate.equals(other.expirydate))) {
            return false;
        }
        if ((this.remark == null) ? (other.remark != null) : !this.remark.equals(other.remark)) {
            return false;
        }
        if (this.lotid != other.lotid && (this.lotid == null || !this.lotid.equals(other.lotid))) {
            return false;
        }
        if ((this.productName == null) ? (other.productName != null) : !this.productName.equals(other.productName)) {
            return false;
        }
        if ((this.categoryName == null) ? (other.categoryName != null) : !this.categoryName.equals(other.categoryName)) {
            return false;
        }
        if (this.qtygood != other.qtygood && (this.qtygood == null || !this.qtygood.equals(other.qtygood))) {
            return false;
        }
        if (this.qtydmg != other.qtydmg && (this.qtydmg == null || !this.qtydmg.equals(other.qtydmg))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Vgrdetailproductcategory{ grnumber=" + grnumber + ", productcode=" + productcode + ", qtyreal=" + qtyreal + ", status=" + status + ", expirydate=" + expirydate + ", remark=" + remark + ", lotid=" + lotid + ", productName=" + productName + ", categoryName=" + categoryName + ", qtygood=" + qtygood + ", qtydmg=" + qtydmg + '}';
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCorpId() {
        return corpId;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    public String getWhCode() {
        return whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

    public Integer getQtyplus() {
        return qtyplus;
    }

    public void setQtyplus(Integer qtyplus) {
        this.qtyplus = qtyplus;
    }
    
    

    


}


