package com.app.wms.hbm.bean;
// Generated Dec 13, 2012 3:09:57 AM by Hibernate Tools 3.2.1.GA

/**
 * Vlocationproduct generated by hbm2java
 */
public class Vlocationproduct implements java.io.Serializable {

    private int id;
    private String locationId;
    private String locationName;
    private String locationCode;
    private String locationArea;
    private String productId;
    private String productCode;
    private Integer minProduct;
    private Integer maxProduct;
    private String userId;
    private String corpId;
    private String whCode;
    private Integer balance;
    

    public Vlocationproduct() {
    }

    public String getLocationArea() {
		return locationArea;
	}

	public void setLocationArea(String locationArea) {
		this.locationArea = locationArea;
	}

	public Vlocationproduct(int id) {
        this.id = id;
    }

    public Vlocationproduct(int id, String locationId, String locationName, String productId, Integer minProduct, Integer maxProduct, String userId, String corpId, String whCode, Integer balance) {
        this.id = id;
        this.locationId = locationId;
        this.locationName = locationName;
        this.productId = productId;
        this.minProduct = minProduct;
        this.maxProduct = maxProduct;
        this.userId = userId;
        this.corpId = corpId;
        this.whCode = whCode;
        this.balance = balance;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLocationId() {
        return this.locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getLocationName() {
        return this.locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Integer getMinProduct() {
        return this.minProduct;
    }

    public void setMinProduct(Integer minProduct) {
        this.minProduct = minProduct;
    }

    public Integer getMaxProduct() {
        return this.maxProduct;
    }

    public void setMaxProduct(Integer maxProduct) {
        this.maxProduct = maxProduct;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getCorpId() {
        return this.corpId;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    public String getWhCode() {
        return this.whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

    public Integer getBalance() {
        return this.balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    
    

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof Vlocationproduct)) {
            return false;
        }
        Vlocationproduct castOther = (Vlocationproduct) other;

        return (this.getId() == castOther.getId())
                && ((this.getLocationId() == castOther.getLocationId()) || (this.getLocationId() != null && castOther.getLocationId() != null && this.getLocationId().equals(castOther.getLocationId())))
                && ((this.getLocationName() == castOther.getLocationName()) || (this.getLocationName() != null && castOther.getLocationName() != null && this.getLocationName().equals(castOther.getLocationName())))
                && ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null && castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
                && ((this.getMinProduct() == castOther.getMinProduct()) || (this.getMinProduct() != null && castOther.getMinProduct() != null && this.getMinProduct().equals(castOther.getMinProduct())))
                && ((this.getMaxProduct() == castOther.getMaxProduct()) || (this.getMaxProduct() != null && castOther.getMaxProduct() != null && this.getMaxProduct().equals(castOther.getMaxProduct())))
                && ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getCorpId() == castOther.getCorpId()) || (this.getCorpId() != null && castOther.getCorpId() != null && this.getCorpId().equals(castOther.getCorpId())))
                && ((this.getWhCode() == castOther.getWhCode()) || (this.getWhCode() != null && castOther.getWhCode() != null && this.getWhCode().equals(castOther.getWhCode())))
                && ((this.getBalance() == castOther.getBalance()) || (this.getBalance() != null && castOther.getBalance() != null && this.getBalance().equals(castOther.getBalance())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + (getLocationId() == null ? 0 : this.getLocationId().hashCode());
        result = 37 * result + (getLocationName() == null ? 0 : this.getLocationName().hashCode());
        result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
        result = 37 * result + (getMinProduct() == null ? 0 : this.getMinProduct().hashCode());
        result = 37 * result + (getMaxProduct() == null ? 0 : this.getMaxProduct().hashCode());
        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getCorpId() == null ? 0 : this.getCorpId().hashCode());
        result = 37 * result + (getWhCode() == null ? 0 : this.getWhCode().hashCode());
        result = 37 * result + (getBalance() == null ? 0 : this.getBalance().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "Vlocationproduct{" + "id=" + id + ", locationId=" + locationId + ", locationName=" + locationName + ", productId=" + productId + ", minProduct=" + minProduct + ", maxProduct=" + maxProduct + ", userId=" + userId + ", corpId=" + corpId + ", whCode=" + whCode + ", balance=" + balance + '}';
    }

    public String getLocationCode() {
        return locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }
    
    

    
}
