package com.app.wms.hbm.bean;
// Generated Feb 6, 2013 1:38:02 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Vproductsku generated by hbm2java
 */
public class Vproductsku  implements java.io.Serializable {

     private int id;
     private String productId;
     private String barCode;
     private String productCode;
     private String productName;
     private String productAlias;
     private String productCategory;
     private String brandName;
     private String productType;
     private String productColor;
     private String productDescription;
     private String unitWeight;
     private String unitLength;
     private String unitWidth;
     private String unitHeight;
     private Integer unitPiece;
     private Integer unitBox;
     private Integer unitCartoon;
     private Integer unitPallete;
     private String userId;
     private String corpId;
     private String whCode;
     private Character isActive;
     private Character isDelete;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String uomName;
     private String sku;
     private Integer balance;

    public Vproductsku() {
    }

	
    public Vproductsku(int id, Date createdDate, Date updatedDate, String sku) {
        this.id = id;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.sku = sku;
    }
    public Vproductsku(int id, String productId, String barCode, String productCode, String productName, String productAlias, String productCategory, String brandName, String productType, String productColor, String productDescription, String unitWeight, String unitLength, String unitWidth, String unitHeight, Integer unitPiece, Integer unitBox, Integer unitCartoon, Integer unitPallete, String userId, String corpId, String whCode, Character isActive, Character isDelete, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String uomName, String sku, Integer balance) {
       this.id = id;
       this.productId = productId;
       this.barCode = barCode;
       this.productCode = productCode;
       this.productName = productName;
       this.productAlias = productAlias;
       this.productCategory = productCategory;
       this.brandName = brandName;
       this.productType = productType;
       this.productColor = productColor;
       this.productDescription = productDescription;
       this.unitWeight = unitWeight;
       this.unitLength = unitLength;
       this.unitWidth = unitWidth;
       this.unitHeight = unitHeight;
       this.unitPiece = unitPiece;
       this.unitBox = unitBox;
       this.unitCartoon = unitCartoon;
       this.unitPallete = unitPallete;
       this.userId = userId;
       this.corpId = corpId;
       this.whCode = whCode;
       this.isActive = isActive;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.uomName = uomName;
       this.sku = sku;
       this.balance = balance;
    }
   
    public Integer getBalance() {
		return balance;
	}


	public void setBalance(Integer balance) {
		this.balance = balance;
	}


	public String getUomName() {
		return uomName;
	}


	public void setUomName(String uomName) {
		this.uomName = uomName;
	}


	public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductAlias() {
        return this.productAlias;
    }
    
    public void setProductAlias(String productAlias) {
        this.productAlias = productAlias;
    }
    public String getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public String getUnitWeight() {
        return this.unitWeight;
    }
    
    public void setUnitWeight(String unitWeight) {
        this.unitWeight = unitWeight;
    }
    public String getUnitLength() {
        return this.unitLength;
    }
    
    public void setUnitLength(String unitLength) {
        this.unitLength = unitLength;
    }
    public String getUnitWidth() {
        return this.unitWidth;
    }
    
    public void setUnitWidth(String unitWidth) {
        this.unitWidth = unitWidth;
    }
    public String getUnitHeight() {
        return this.unitHeight;
    }
    
    public void setUnitHeight(String unitHeight) {
        this.unitHeight = unitHeight;
    }
    public Integer getUnitPiece() {
        return this.unitPiece;
    }
    
    public void setUnitPiece(Integer unitPiece) {
        this.unitPiece = unitPiece;
    }
    public Integer getUnitBox() {
        return this.unitBox;
    }
    
    public void setUnitBox(Integer unitBox) {
        this.unitBox = unitBox;
    }
    public Integer getUnitCartoon() {
        return this.unitCartoon;
    }
    
    public void setUnitCartoon(Integer unitCartoon) {
        this.unitCartoon = unitCartoon;
    }
    public Integer getUnitPallete() {
        return this.unitPallete;
    }
    
    public void setUnitPallete(Integer unitPallete) {
        this.unitPallete = unitPallete;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }
    public Character getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vproductsku) ) return false;
		 Vproductsku castOther = ( Vproductsku ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getProductId()==castOther.getProductId()) || ( this.getProductId()!=null && castOther.getProductId()!=null && this.getProductId().equals(castOther.getProductId()) ) )
 && ( (this.getBarCode()==castOther.getBarCode()) || ( this.getBarCode()!=null && castOther.getBarCode()!=null && this.getBarCode().equals(castOther.getBarCode()) ) )
 && ( (this.getProductCode()==castOther.getProductCode()) || ( this.getProductCode()!=null && castOther.getProductCode()!=null && this.getProductCode().equals(castOther.getProductCode()) ) )
 && ( (this.getProductName()==castOther.getProductName()) || ( this.getProductName()!=null && castOther.getProductName()!=null && this.getProductName().equals(castOther.getProductName()) ) )
 && ( (this.getProductAlias()==castOther.getProductAlias()) || ( this.getProductAlias()!=null && castOther.getProductAlias()!=null && this.getProductAlias().equals(castOther.getProductAlias()) ) )
 && ( (this.getProductCategory()==castOther.getProductCategory()) || ( this.getProductCategory()!=null && castOther.getProductCategory()!=null && this.getProductCategory().equals(castOther.getProductCategory()) ) )
 && ( (this.getBrandName()==castOther.getBrandName()) || ( this.getBrandName()!=null && castOther.getBrandName()!=null && this.getBrandName().equals(castOther.getBrandName()) ) )
 && ( (this.getProductType()==castOther.getProductType()) || ( this.getProductType()!=null && castOther.getProductType()!=null && this.getProductType().equals(castOther.getProductType()) ) )
 && ( (this.getProductColor()==castOther.getProductColor()) || ( this.getProductColor()!=null && castOther.getProductColor()!=null && this.getProductColor().equals(castOther.getProductColor()) ) )
 && ( (this.getProductDescription()==castOther.getProductDescription()) || ( this.getProductDescription()!=null && castOther.getProductDescription()!=null && this.getProductDescription().equals(castOther.getProductDescription()) ) )
 && ( (this.getUnitWeight()==castOther.getUnitWeight()) || ( this.getUnitWeight()!=null && castOther.getUnitWeight()!=null && this.getUnitWeight().equals(castOther.getUnitWeight()) ) )
 && ( (this.getUnitLength()==castOther.getUnitLength()) || ( this.getUnitLength()!=null && castOther.getUnitLength()!=null && this.getUnitLength().equals(castOther.getUnitLength()) ) )
 && ( (this.getUnitWidth()==castOther.getUnitWidth()) || ( this.getUnitWidth()!=null && castOther.getUnitWidth()!=null && this.getUnitWidth().equals(castOther.getUnitWidth()) ) )
 && ( (this.getUnitHeight()==castOther.getUnitHeight()) || ( this.getUnitHeight()!=null && castOther.getUnitHeight()!=null && this.getUnitHeight().equals(castOther.getUnitHeight()) ) )
 && ( (this.getUnitPiece()==castOther.getUnitPiece()) || ( this.getUnitPiece()!=null && castOther.getUnitPiece()!=null && this.getUnitPiece().equals(castOther.getUnitPiece()) ) )
 && ( (this.getUnitBox()==castOther.getUnitBox()) || ( this.getUnitBox()!=null && castOther.getUnitBox()!=null && this.getUnitBox().equals(castOther.getUnitBox()) ) )
 && ( (this.getUnitCartoon()==castOther.getUnitCartoon()) || ( this.getUnitCartoon()!=null && castOther.getUnitCartoon()!=null && this.getUnitCartoon().equals(castOther.getUnitCartoon()) ) )
 && ( (this.getUnitPallete()==castOther.getUnitPallete()) || ( this.getUnitPallete()!=null && castOther.getUnitPallete()!=null && this.getUnitPallete().equals(castOther.getUnitPallete()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getCorpId()==castOther.getCorpId()) || ( this.getCorpId()!=null && castOther.getCorpId()!=null && this.getCorpId().equals(castOther.getCorpId()) ) )
 && ( (this.getWhCode()==castOther.getWhCode()) || ( this.getWhCode()!=null && castOther.getWhCode()!=null && this.getWhCode().equals(castOther.getWhCode()) ) )
 && ( (this.getIsActive()==castOther.getIsActive()) || ( this.getIsActive()!=null && castOther.getIsActive()!=null && this.getIsActive().equals(castOther.getIsActive()) ) )
 && ( (this.getIsDelete()==castOther.getIsDelete()) || ( this.getIsDelete()!=null && castOther.getIsDelete()!=null && this.getIsDelete().equals(castOther.getIsDelete()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDate()==castOther.getUpdatedDate()) || ( this.getUpdatedDate()!=null && castOther.getUpdatedDate()!=null && this.getUpdatedDate().equals(castOther.getUpdatedDate()) ) )
 && ( (this.getSku()==castOther.getSku()) || ( this.getSku()!=null && castOther.getSku()!=null && this.getSku().equals(castOther.getSku()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getProductId() == null ? 0 : this.getProductId().hashCode() );
         result = 37 * result + ( getBarCode() == null ? 0 : this.getBarCode().hashCode() );
         result = 37 * result + ( getProductCode() == null ? 0 : this.getProductCode().hashCode() );
         result = 37 * result + ( getProductName() == null ? 0 : this.getProductName().hashCode() );
         result = 37 * result + ( getProductAlias() == null ? 0 : this.getProductAlias().hashCode() );
         result = 37 * result + ( getProductCategory() == null ? 0 : this.getProductCategory().hashCode() );
         result = 37 * result + ( getBrandName() == null ? 0 : this.getBrandName().hashCode() );
         result = 37 * result + ( getProductType() == null ? 0 : this.getProductType().hashCode() );
         result = 37 * result + ( getProductColor() == null ? 0 : this.getProductColor().hashCode() );
         result = 37 * result + ( getProductDescription() == null ? 0 : this.getProductDescription().hashCode() );
         result = 37 * result + ( getUnitWeight() == null ? 0 : this.getUnitWeight().hashCode() );
         result = 37 * result + ( getUnitLength() == null ? 0 : this.getUnitLength().hashCode() );
         result = 37 * result + ( getUnitWidth() == null ? 0 : this.getUnitWidth().hashCode() );
         result = 37 * result + ( getUnitHeight() == null ? 0 : this.getUnitHeight().hashCode() );
         result = 37 * result + ( getUnitPiece() == null ? 0 : this.getUnitPiece().hashCode() );
         result = 37 * result + ( getUnitBox() == null ? 0 : this.getUnitBox().hashCode() );
         result = 37 * result + ( getUnitCartoon() == null ? 0 : this.getUnitCartoon().hashCode() );
         result = 37 * result + ( getUnitPallete() == null ? 0 : this.getUnitPallete().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getCorpId() == null ? 0 : this.getCorpId().hashCode() );
         result = 37 * result + ( getWhCode() == null ? 0 : this.getWhCode().hashCode() );
         result = 37 * result + ( getIsActive() == null ? 0 : this.getIsActive().hashCode() );
         result = 37 * result + ( getIsDelete() == null ? 0 : this.getIsDelete().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode() );
         result = 37 * result + ( getSku() == null ? 0 : this.getSku().hashCode() );
         return result;
   }   



}


