package com.app.wms.hbm.bean;
// Generated Nov 29, 2012 8:48:23 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Vputawaydetailproduct generated by hbm2java
 */
public class Vputawaydetailproduct  implements java.io.Serializable {


    private int id;
    private String productName;
     private String productCode;
     private String putawayId;
     private Date receivedDate;
     private String userId;
     private String corpId;
     private Integer qtyOrder;
     private String whCode;
     private String locationCode;
     private String categoryName;
     private String productType;

    public Vputawaydetailproduct() {
    }

    public Vputawaydetailproduct(String productName, String productCode, String putawayId, Date receivedDate, String userId, String corpId, Integer qtyOrder, String whCode) {
       this.productName = productName;
       this.productCode = productCode;
       this.putawayId = putawayId;
       this.receivedDate = receivedDate;
       this.userId = userId;
       this.corpId = corpId;
       this.qtyOrder = qtyOrder;
       this.whCode = whCode;
    }
   
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getPutawayId() {
        return this.putawayId;
    }
    
    public void setPutawayId(String putawayId) {
        this.putawayId = putawayId;
    }
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public Integer getQtyOrder() {
        return this.qtyOrder;
    }
    
    public void setQtyOrder(Integer qtyOrder) {
        this.qtyOrder = qtyOrder;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vputawaydetailproduct) ) return false;
		 Vputawaydetailproduct castOther = ( Vputawaydetailproduct ) other; 
         
		 return ( (this.getProductName()==castOther.getProductName()) || ( this.getProductName()!=null && castOther.getProductName()!=null && this.getProductName().equals(castOther.getProductName()) ) )
 && ( (this.getProductCode()==castOther.getProductCode()) || ( this.getProductCode()!=null && castOther.getProductCode()!=null && this.getProductCode().equals(castOther.getProductCode()) ) )
 && ( (this.getPutawayId()==castOther.getPutawayId()) || ( this.getPutawayId()!=null && castOther.getPutawayId()!=null && this.getPutawayId().equals(castOther.getPutawayId()) ) )
 && ( (this.getReceivedDate()==castOther.getReceivedDate()) || ( this.getReceivedDate()!=null && castOther.getReceivedDate()!=null && this.getReceivedDate().equals(castOther.getReceivedDate()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getCorpId()==castOther.getCorpId()) || ( this.getCorpId()!=null && castOther.getCorpId()!=null && this.getCorpId().equals(castOther.getCorpId()) ) )
 && ( (this.getQtyOrder()==castOther.getQtyOrder()) || ( this.getQtyOrder()!=null && castOther.getQtyOrder()!=null && this.getQtyOrder().equals(castOther.getQtyOrder()) ) )
 && ( (this.getWhCode()==castOther.getWhCode()) || ( this.getWhCode()!=null && castOther.getWhCode()!=null && this.getWhCode().equals(castOther.getWhCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductName() == null ? 0 : this.getProductName().hashCode() );
         result = 37 * result + ( getProductCode() == null ? 0 : this.getProductCode().hashCode() );
         result = 37 * result + ( getPutawayId() == null ? 0 : this.getPutawayId().hashCode() );
         result = 37 * result + ( getReceivedDate() == null ? 0 : this.getReceivedDate().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getCorpId() == null ? 0 : this.getCorpId().hashCode() );
         result = 37 * result + ( getQtyOrder() == null ? 0 : this.getQtyOrder().hashCode() );
         result = 37 * result + ( getWhCode() == null ? 0 : this.getWhCode().hashCode() );
         return result;
   }   

    public String getLocationCode() {
        return locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Override
    public String toString() {
        return "Vputawaydetailproduct{" + "id=" + id + ", productName=" + productName + ", productCode=" + productCode + ", putawayId=" + putawayId + ", receivedDate=" + receivedDate + ", userId=" + userId + ", corpId=" + corpId + ", qtyOrder=" + qtyOrder + ", whCode=" + whCode + ", locationCode=" + locationCode + ", categoryName=" + categoryName + '}';
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }


    
    


}


