package com.app.wms.hbm.bean;
// Generated Feb 13, 2013 2:10:54 AM by Hibernate Tools 3.2.1.GA



/**
 * WhLocatingArea generated by hbm2java
 */
public class WhLocatingArea  implements java.io.Serializable {


     private int id;
     private String locatingId;
     private String locatingArea;
     private String locatingCondition;
     private String userId;
     private String corpId;
     private String whCode;

    public WhLocatingArea() {
    }

	
    public WhLocatingArea(int id) {
        this.id = id;
    }
    public WhLocatingArea(int id, String locatingId, String locatingArea, String locatingCondition, String userId, String corpId, String whCode) {
       this.id = id;
       this.locatingId = locatingId;
       this.locatingArea = locatingArea;
       this.locatingCondition = locatingCondition;
       this.userId = userId;
       this.corpId = corpId;
       this.whCode = whCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLocatingId() {
        return this.locatingId;
    }
    
    public void setLocatingId(String locatingId) {
        this.locatingId = locatingId;
    }
    public String getLocatingArea() {
        return this.locatingArea;
    }
    
    public void setLocatingArea(String locatingArea) {
        this.locatingArea = locatingArea;
    }
    public String getLocatingCondition() {
        return this.locatingCondition;
    }
    
    public void setLocatingCondition(String locatingCondition) {
        this.locatingCondition = locatingCondition;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCorpId() {
        return this.corpId;
    }
    
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }
    public String getWhCode() {
        return this.whCode;
    }
    
    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }




}


